### ISSUE TITLE
Update README and add "contributing guidelines" to Wren:DS

### ISSUE THREAD

**Issue by Kortanul** [WrenSecurity/wrends#14]
we need help getting this project moving even faster. probably the best way to do this is to add contributing guidelines, per:
https://github.com/blog/1184-contributing-guidelines

there are some examples from Filip of Orchitech that need to be reviewed and incorporated: https://github.com/smolafilip/wrensec-website/wiki/Branching

in addition, the build instructions in the README file likely need updating as well.

**Comment by karelmaxa** [comment]
Project README was completely reworked in PR #46.
