### ISSUE TITLE
[3.5.1] Get DS 3.5.x checked-in, merged, and buildable

### ISSUE THREAD

**Issue by Kortanul** [WrenSecurity/wrends#15]
we have a CDDL copy of OpenDJ 3.5.x.

we should:
1. create a `sustaining/3.5` branch off of the `forgerock/3.0.0` tag
2. check-in our copy of 3.5.x on that branch.
3. update the branch with build changes from `sustaining/3.0` so that it can build.

**Comment by pavelhoral** [comment]
Plan is to continue work on the current master so this issue is no longer valid.
