### ISSUE TITLE
Debian Standard Packages Can't Use Doc Generated Ref from Same Reactor

### ISSUE THREAD

**Issue by Kortanul** [WrenSecurity/wrends#18]
## Affected Version
Wren:DS 3.5.1

## Repro Steps
1. From a checked-out copy of Wren:DS, use `mvn versions:set -DnewVersion=X.Y.Z` inside the `opendj-bom` module to bump the version of the project to one that does _not_ exist in JFrog.
2. Run `mvn clean install -Ppackages -Pforgerock-release -Dignore-artifact-sigs` from the root of the Wren:DS repo.

## Expected
All projects build successfully.
 
## Actual
The "Wren:DS Debian Standard Package" module fails because it's looking for "Wren:DS Doc Generated References" in JFrog instead of using what was built in the same maven reactor / build.

**Comment by pavelhoral** [comment]
I was able to build the project in one command with `man-pages` profile:

```shell
mvn verify -Ppackages -Pman-pages -DignoreArtifactSigs -DskipTests
```
