### ISSUE TITLE
deprecate and remove Persistit Data Backend (PDB)

### ISSUE THREAD

**Issue by Kortanul** [WrenSecurity/wrends#2]
ForgeRock introduced the Persistit Data Backend (PDB) in OpenDJ 3.0.0 and deprecated it in DS 5 (i.e. OpenDJ 4.0.0).

There are multiple reasons why they abandoned it:
- ForgeRock had to fork the project because Akiban was acquired and no longer maintains it.
- Even after patches from FR, it has remaining issues that can cause deadlock in production,
- Unit tests for Persistit are painfully slow and fail if you actually run them.
- PDB is no longer needed because JE licensing is now compatible with OEM deployments of OpenDJ / Wren:DS. _We still need to upgrade the JE backend &ndash; see https://github.com/WrenSecurity/wrends/issues/1._

**Comment by siepkes** [comment]
Seems like a good idea; Less maintenance burden for us.
