### ISSUE TITLE
Remove the ForgeRock Commercial License

### ISSUE THREAD

**Issue by Kortanul** [WrenSecurity/wrends#33]
## Summary
I would like Wren:DS distributions not to contain any reference to ForgeRock's commercial license. 

## Solution You'd Like to See
- The TXT files that contain the terms of the FR commercial license are no longer included in JAR packages for Wren:DS.
- The FR commercial license is no longer displayed on the first screen of the interactive installer. In its place, we should be displaying the CDDL instead.

## Workarounds/Alternatives
Users currently have to ignore the commercial license during install, since it doesn't apply to them. This causes confusion.

**Comment by pavelhoral** [comment]
I consider this resolved after #77 had been merged.
