### ISSUE TITLE
Unable to maven install

### ISSUE THREAD

**Issue by jefflks** [WrenSecurity/wrends#36]
[WARNING] [Retry 1 of 10] Waiting 750 milliseconds before retrying key request from hkps.pool.sks-keyservers.net/192.146.137.98 after last request failed: HTTP/1.1 502 Bad Gateway
[WARNING] [Retry 2 of 10] Waiting 1500 milliseconds before retrying key request from hkps.pool.sks-keyservers.net/192.146.137.98 after last request failed: HTTP/1.1 502 Bad Gateway
[WARNING] [Retry 3 of 10] Waiting 2250 milliseconds before retrying key request from hkps.pool.sks-keyservers.net/192.146.137.98 after last request failed: HTTP/1.1 502 Bad Gateway
[WARNING] [Retry 4 of 10] Waiting 3000 milliseconds before retrying key request from hkps.pool.sks-keyservers.net/192.146.137.98 after last request failed: HTTP/1.1 502 Bad Gateway
[WARNING] [Retry 5 of 10] Waiting 3750 milliseconds before retrying key request from hkps.pool.sks-keyservers.net/192.146.137.98 after last request failed: HTTP/1.1 502 Bad Gateway
[WARNING] [Retry 6 of 10] Waiting 4500 milliseconds before retrying key request from hkps.pool.sks-keyservers.net/192.146.137.98 after last request failed: HTTP/1.1 502 Bad Gateway
[WARNING] [Retry 7 of 10] Waiting 5250 milliseconds before retrying key request from hkps.pool.sks-keyservers.net/192.146.137.98 after last request failed: HTTP/1.1 502 Bad Gateway
[WARNING] [Retry 8 of 10] Waiting 6000 milliseconds before retrying key request from hkps.pool.sks-keyservers.net/192.146.137.98 after last request failed: HTTP/1.1 502 Bad Gateway
[WARNING] [Retry 9 of 10] Waiting 6750 milliseconds before retrying key request from hkps.pool.sks-keyservers.net/192.146.137.98 after last request failed: HTTP/1.1 502 Bad Gateway
[WARNING] [Retry 10 of 10] Waiting 7500 milliseconds before retrying key request from hkps.pool.sks-keyservers.net/192.146.137.98 after last request failed: HTTP/1.1 502 Bad Gateway

**Comment by pavelhoral** [comment]
Which branch or tag are you trying to build? This seems like issue with some proxy settings rather than with project itself.

**Comment by pavelhoral** [comment]
The sustaining/3.x branch is now buildable with disabled signature control. See README for exact commands to build the project. Master is buildable with signature control.
