### ISSUE TITLE
Move all repositories from WrenArchiver here

### ISSUE THREAD

**Issue by Neustradamus** [WrenSecurity/wrends#37]
It is possible to move all repositories from WrenArchiver here?
- https://github.com/WrenArchiver

And you can convert the WrenArchiver personal account to organization too.

**Comment by pavelhoral** [comment]
The main idea behind _WrenArchiver_ was to have 1:1 state of code as it was forked from Forgerock. As such that repo will stay frozen in time and it does not make much sense in moving it here. 

The only thing I personally don't  like is the _"forked from WrenArchiver/..."_ subheader here. Is there any specific goal behind your request?

**Comment by siepkes** [comment]
@pavelhoral I think we could mail GitHub support to cut us loose from the "forked from WrenArchiver" subheader. That will probably also make us easier to find since I get the feeling we're being pushed back in GitHub search results because of it.

**Comment by Neustradamus** [comment]
You can merge all in main code too, it is better :)
You can move repositories... and redirections are here...

**Comment by pavelhoral** [comment]
> I think we could mail GitHub support to cut us loose from the "forked from WrenArchiver" subheader

The "forked from" was removed by GitHub Support. 

> And you can convert the WrenArchiver personal account to organization too.

It would be nice to convert WrenArchiver to organization, but that is out of scope for Wren:DS project.

I think there is nothing else to solve here (feel free to reopen if you think I missed something).
