### ISSUE TITLE
top-level build fails on `opendj-dsml-servlet`

### ISSUE THREAD

**Issue by Kortanul** [WrenSecurity/wrends#4]
It's not possible to build all of OpenDJ successfully in one pass. the `opendj-dsml-servlet` project will fail because it can't find packages, but re-building just that package succeeds.

something is causing the classpath to be stale during the build.

## Steps
1. checkout Wren:DS from `sustaining/3.0.0`.
2. run `mvn clean install`.

## Expected
- the build succeeds

## Currently
- the build fails because it cannot find several packages of generated source code:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project opendj-dsml-servlet: Compilation failure: Compilation failure:
[ERROR] opendj-dsml-servlet/src/main/java/org/opends/dsml/protocol/DSMLAddOperation.java:[37,40] package org.opends.server.protocols.ldap does not exist
```
- afterwards, building with `mvn clean install -pl opendj-dsml-servlet` succeeds.

**Comment by pavelhoral** [comment]
This is no longer happening. Not sure which change fixed this but possibly Maven plugin update.
