### ISSUE TITLE
About the Bind method provided by the LDAP service to the client

### ISSUE THREAD

**Issue by 136750162** [WrenSecurity/wrends#66]
Hello, I would like to ask, if I want to modify the Bind method provided for client access, what do I need to modify? Thank you very much for your answer

**Comment by pavelhoral** [comment]
It is not possible to answer without a specific code or issue you are facing. Also issues is probably not the best place to have this conversation. I have enabled Discussions on the project so maybe you can move it there - https://github.com/WrenSecurity/wrends/discussions.
